### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by orkenstein** [leeyupeng/fountain-atom#2]
1. Install plugin
2. Command palette -> Fountain: Preview

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: [fountain-zh](https://github.com/leeyupeng/fountain-atom) package 0.8.1

### Stack Trace

Uncaught TypeError: Path must be a string. Received null

```
At path.js:28

TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.join (path.js:1251:7)
    at PdfConverter.toFile (/packages/fountain-zh/lib/fountain-pdf-converter.coffee:44:28)
    at PdfConverter.initiateConversion (/packages/fountain-zh/lib/fountain-pdf-converter.coffee:22:8)
    at PdfConverter.createPreview (/packages/fountain-zh/lib/fountain-pdf-converter.coffee:11:6)
    at Object.pdfPreview (/packages/fountain-zh/lib/fountain.coffee:220:20)
    at /packages/fountain-zh/lib/fountain.coffee:166:31)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349922)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:677666)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:842467)
    at SelectListView.didClickItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:840409)
    at ListItemView.onclick (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:839399)
    at ListItemView.didClick (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:843487)
```

### Commands

```
     -0:47.5.0 fountain:toggle-outline-view (input.hidden-input)
  2x -0:46.2.0 activate-power-mode:toggle (div.fountain-outline-view)
     -0:43.1.0 command-palette:toggle (div.github-StagingView.unstaged-changes-focused)
     -0:40.6.0 core:select-all (input.hidden-input)
  4x -0:38.5.0 core:move-down (input.hidden-input)
  4x -0:36.8.0 core:move-up (input.hidden-input)
     -0:36 core:confirm (input.hidden-input)
     -0:36 fountain:preview (div.github-StagingView.unstaged-changes-focused)
     -0:05.1.0 fountain:toggle-outline-view (input.hidden-input)
     -0:03.8.0 command-palette:toggle (div.fountain-outline-view)
     -0:01.7.0 fountain:preview (div.fountain-outline-view)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-runner 2.7.1 
atom-translator-tooltips 0.3.1 
busy-signal 2.0.1 
circle-ci 0.10.1 
count-word 0.2.3 
docker 0.8.0 
dockerletion 0.2.0 
file-icons 2.1.32 
filmustage-script-markdown 0.3.6 
fountain-zh 0.8.1 
highlight-selected 0.16.0 
ide-docker 0.1.0 
ide-json 0.2.1 
ide-python 1.4.1 
ide-ruby 0.3.0 
ide-yaml 0.5.0 
intentions 1.1.5 
language-csv 1.1.2 
language-docker 1.1.8 
language-hcl 0.4.0 
language-log 1.10.1 
language-markdown 0.37.0 
language-matlab 0.2.1 
language-terraform 0.8.1 
linter 2.3.0 
linter-docker 0.3.2 
linter-flake8 2.4.0 
linter-pycodestyle 2.1.3 
linter-ruby 1.3.1 
linter-terraform-syntax 1.3.0 
linter-ui-default 1.7.1 
minimap-split-diff 0.3.7 
project-plus 1.0.0 
sonarlint 1.3.0 
split-diff 1.6.0 
teletype 0.13.4 
```

**Comment by leeyupeng** [comment]
Hi orkenstein,

This is a fork project and it's customized for Chinese screenplay writing.
Maybe you should try the original project https://github.com/superlou/fountain-atom 

Thanks.
